delete from users;
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Tom Cat', 25, FALSE , CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Jerry Mouse', 25, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Admin the God', 30, TRUE , CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Ivan', 21, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Peter', 22, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('John', 23, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('David', 24, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Charles', 26, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Hank', 27, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Denis', 28, FALSE, CURRENT_TIMESTAMP);
INSERT INTO users (name, age, is_admin, create_date) VALUES ('Urfin', 29, TRUE, CURRENT_TIMESTAMP);